// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_WEB_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    databaseURL: 'YOUR_DATABASE_URL',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxy_9CMJegjWJJKEinudU-8FMlznscIc8',
    appId: '1:741296019981:android:175e17c2519413b9d31344',
    messagingSenderId: '741296019981',
    projectId: 'proud-voice-471806-j8',
    databaseURL: 'https://proud-voice-471806-j8.firebaseio.com',
    storageBucket: 'proud-voice-471806-j8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxDX4HAdfvgFd0drlAXEDvW3axcDEffYs',
    appId: '1:741296019981:ios:6a65f3373295c0ffd31344',
    messagingSenderId: '741296019981',
    projectId: 'proud-voice-471806-j8',
    databaseURL: 'https://proud-voice-471806-j8.firebaseio.com',
    storageBucket: 'proud-voice-471806-j8.firebasestorage.app',
    iosBundleId: 'com.nishan.digaxy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxDX4HAdfvgFd0drlAXEDvW3axcDEffYs',
    appId: '1:741296019981:ios:6a65f3373295c0ffd31344',
    messagingSenderId: '741296019981',
    projectId: 'proud-voice-471806-j8',
    databaseURL: 'https://proud-voice-471806-j8.firebaseio.com',
    storageBucket: 'proud-voice-471806-j8.firebasestorage.app',
    iosBundleId: 'com.nishan.digaxy',
  );
}
