part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const MOVER = _Paths.MOVER;
  static const MOVER_HOME = _Paths.MOVER_HOME;
  static const MOVER_CREATE_PARCEL = _Paths.MOVER_CREATE_PARCEL;
  static const MOVER_SERVICES = _Paths.MOVER_SERVICES;
  static const MOVER_CONTACT_DETAILS = _Paths.MOVER_CONTACT_DETAILS;
  static const MOVER_PICKUP_LOCATION = _Paths.MOVER_PICKUP_LOCATION;
  static const MOVER_DROPOFF_LOCATION = _Paths.MOVER_DROPOFF_LOCATION;
  static const MOVER_ESTIMATE = _Paths.MOVER_ESTIMATE;
  static const MOVER_SCHEDULE = _Paths.MOVER_SCHEDULE;
  static const MOVER_BOOKING_CONFIRMED = _Paths.MOVER_BOOKING_CONFIRMED;
  static const MOVER_PARCEL_TRACKING = _Paths.MOVER_PARCEL_TRACKING;
  static const MOVER_PROFILE = _Paths.MOVER_PROFILE;
  static const MOVER_PROFILE_EDIT = _Paths.MOVER_PROFILE_EDIT;
  static const MOVER_SETTINGS = _Paths.MOVER_SETTINGS;
  static const MOVER_SETTINGS_CHANGE_PASSWORD =
      _Paths.MOVER_SETTINGS_CHANGE_PASSWORD;
  static const MOVER_SETTINGS_PRIVACY = _Paths.MOVER_SETTINGS_PRIVACY;
  static const MOVER_SETTINGS_TERMS = _Paths.MOVER_SETTINGS_TERMS;
  static const MOVER_SETTINGS_HELP = _Paths.MOVER_SETTINGS_HELP;
  static const MOVER_NOTIFICATIONS = _Paths.MOVER_NOTIFICATIONS;
  static const MOVER_CITY_DETAILS = _Paths.MOVER_CITY_DETAILS;
  static const DRIVER_HOME = _Paths.DRIVER_HOME;
  static const HELPER_HOME = _Paths.HELPER_HOME;
  static const HELPER_PROFILE = _Paths.HELPER_PROFILE;
  static const HELPER_PROFILE_EDIT = _Paths.HELPER_PROFILE_EDIT;
  static const HELPER_SETTINGS = _Paths.HELPER_SETTINGS;
  static const HELPER_SETTINGS_CHANGE_PASSWORD =
      _Paths.HELPER_SETTINGS_CHANGE_PASSWORD;
  static const HELPER_SETTINGS_PRIVACY = _Paths.HELPER_SETTINGS_PRIVACY;
  static const HELPER_SETTINGS_TERMS = _Paths.HELPER_SETTINGS_TERMS;
  static const HELPER_SETTINGS_HELP = _Paths.HELPER_SETTINGS_HELP;
  static const HELPER_NOTIFICATIONS = _Paths.HELPER_NOTIFICATIONS;
  static const HELPER_PRIORITY = _Paths.HELPER_PRIORITY;
  static const HELPER_DELIVERY_DETAIL = _Paths.HELPER_DELIVERY_DETAIL;
  static const HELPER_REGISTRATION = _Paths.HELPER_REGISTRATION;
  static const LANDING_SPLASH1 = _Paths.LANDING_SPLASH1;
  static const LANDING_SPLASH2 = _Paths.LANDING_SPLASH2;
  static const LANDING_ROLE = _Paths.LANDING_ROLE;
  static const LANDING_ONBOARDING = _Paths.LANDING_ONBOARDING;
  static const AUTH_LOGIN = _Paths.AUTH_LOGIN;
  static const AUTH_SIGNUP = _Paths.AUTH_SIGNUP;
  static const AUTH_FORGOT = _Paths.AUTH_FORGOT;
  static const AUTH_VERIFY = _Paths.AUTH_VERIFY;
  static const AUTH_NEW_PASSWORD = _Paths.AUTH_NEW_PASSWORD;
  static const DRIVER_NOTIFICATIONS = _Paths.DRIVER_NOTIFICATIONS;
  static const DRIVER_EARNINGS = _Paths.DRIVER_EARNINGS;
  static const DRIVER_PROFILE = _Paths.DRIVER_PROFILE;
  static const DRIVER_PRIORITY = _Paths.DRIVER_PRIORITY;
  static const DRIVER_SETTINGS = _Paths.DRIVER_SETTINGS;
  static const DRIVER_SETTINGS_CHANGE_PASSWORD =
      _Paths.DRIVER_SETTINGS_CHANGE_PASSWORD;
  static const DRIVER_SETTINGS_PRIVACY = _Paths.DRIVER_SETTINGS_PRIVACY;
  static const DRIVER_SETTINGS_TERMS = _Paths.DRIVER_SETTINGS_TERMS;
  static const DRIVER_SETTINGS_HELP = _Paths.DRIVER_SETTINGS_HELP;
  static const DRIVER_PROFILE_EDIT = _Paths.DRIVER_PROFILE_EDIT;
  static const DRIVER_TASK_DETAIL = _Paths.DRIVER_TASK_DETAIL;
  static const DRIVER_TASK_ACTIVE = _Paths.DRIVER_TASK_ACTIVE;
  static const DRIVER_TASK_LIVE = _Paths.DRIVER_TASK_LIVE;
  static const DRIVER_PAYOUT = _Paths.DRIVER_PAYOUT;
  static const DRIVER_PAYOUT_AMOUNT = _Paths.DRIVER_PAYOUT_AMOUNT;
  static const DRIVER_PAYOUT_CONFIRM = _Paths.DRIVER_PAYOUT_CONFIRM;
  static const DRIVER_PAYOUT_SUCCESS = _Paths.DRIVER_PAYOUT_SUCCESS;
  static const HELPER_PAYOUT = _Paths.HELPER_PAYOUT;
  static const HELPER_PAYOUT_AMOUNT = _Paths.HELPER_PAYOUT_AMOUNT;
  static const HELPER_PAYOUT_CONFIRM = _Paths.HELPER_PAYOUT_CONFIRM;
  static const HELPER_PAYOUT_SUCCESS = _Paths.HELPER_PAYOUT_SUCCESS;
  static const HELPER_EARNINGS = _Paths.HELPER_EARNINGS;
  static const DRIVER_DELIVERY_DETAIL = _Paths.DRIVER_DELIVERY_DETAIL;
  static const HELPER_SETTINGS_HELP_ACK = _Paths.HELPER_SETTINGS_HELP_ACK;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const MOVER = '/mover';
  static const MOVER_HOME = '/mover/home';
  static const MOVER_CREATE_PARCEL = '/mover/create-parcel';
  static const MOVER_SERVICES = '/mover/services';
  static const MOVER_CONTACT_DETAILS = '/mover/contact-details';
  static const MOVER_PICKUP_LOCATION = '/mover/pickup-location';
  static const MOVER_DROPOFF_LOCATION = '/mover/dropoff-location';
  static const MOVER_ESTIMATE = '/mover/estimate';
  static const MOVER_SCHEDULE = '/mover/schedule';
  static const MOVER_BOOKING_CONFIRMED = '/mover/booking-confirmed';
  static const MOVER_PARCEL_TRACKING = '/mover/parcel-tracking';
  static const MOVER_PROFILE = '/mover/profile';
  static const MOVER_PROFILE_EDIT = '/mover/profile/edit';
  static const MOVER_SETTINGS = '/mover/settings';
  static const MOVER_SETTINGS_CHANGE_PASSWORD =
      '/mover/settings/change-password';
  static const MOVER_SETTINGS_PRIVACY = '/mover/settings/privacy';
  static const MOVER_SETTINGS_TERMS = '/mover/settings/terms';
  static const MOVER_SETTINGS_HELP = '/mover/settings/help';
  static const MOVER_NOTIFICATIONS = '/mover/notifications';
  static const MOVER_CITY_DETAILS = '/mover/city-details';
  static const DRIVER_HOME = '/driver/home';
  static const HELPER_HOME = '/helper/home';
  static const HELPER_PROFILE = '/helper/profile';
  static const HELPER_PROFILE_EDIT = '/helper/profile/edit';
  static const HELPER_SETTINGS = '/helper/settings';
  static const HELPER_SETTINGS_CHANGE_PASSWORD =
      '/helper/settings/change-password';
  static const HELPER_SETTINGS_PRIVACY = '/helper/settings/privacy';
  static const HELPER_SETTINGS_TERMS = '/helper/settings/terms';
  static const HELPER_SETTINGS_HELP = '/helper/settings/help';
  static const HELPER_NOTIFICATIONS = '/helper/notifications';
  static const HELPER_DELIVERY_DETAIL = '/helper/delivery/detail';
  static const HELPER_REGISTRATION = '/helper/registration';
  static const HELPER_EARNINGS = '/helper/earnings';
  static const LANDING_SPLASH1 = '/landing/splash1';
  static const LANDING_SPLASH2 = '/landing/splash2';
  static const LANDING_ROLE = '/landing/role';
  static const LANDING_ONBOARDING = '/landing/onboarding';
  static const AUTH_LOGIN = '/auth/login';
  static const AUTH_SIGNUP = '/auth/signup';
  static const AUTH_FORGOT = '/auth/forgot';
  static const AUTH_VERIFY = '/auth/verify';
  static const AUTH_NEW_PASSWORD = '/auth/new-password';
  static const DRIVER_NOTIFICATIONS = '/driver/notifications';
  static const DRIVER_EARNINGS = '/driver/earnings';
  static const DRIVER_PROFILE = '/driver/profile';
  static const DRIVER_PRIORITY = '/driver/priority';
  static const DRIVER_SETTINGS = '/driver/settings';
  static const DRIVER_SETTINGS_CHANGE_PASSWORD =
      '/driver/settings/change-password';
  static const DRIVER_SETTINGS_PRIVACY = '/driver/settings/privacy';
  static const DRIVER_SETTINGS_TERMS = '/driver/settings/terms';
  static const DRIVER_SETTINGS_HELP = '/driver/settings/help';
  static const DRIVER_PROFILE_EDIT = '/driver/profile/edit';
  static const DRIVER_TASK_DETAIL = '/driver/task/detail';
  static const DRIVER_TASK_ACTIVE = '/driver/task/active';
  static const DRIVER_TASK_LIVE = '/driver/task/live';
  static const DRIVER_PAYOUT = '/driver/earnings/payout';
  static const DRIVER_PAYOUT_AMOUNT = '/driver/earnings/payout/amount';
  static const DRIVER_PAYOUT_CONFIRM = '/driver/earnings/payout/confirm';
  static const DRIVER_PAYOUT_SUCCESS = '/driver/earnings/payout/success';
  static const HELPER_PAYOUT = '/helper/earnings/payout';
  static const HELPER_PAYOUT_AMOUNT = '/helper/earnings/payout/amount';
  static const HELPER_PAYOUT_CONFIRM = '/helper/earnings/payout/confirm';
  static const HELPER_PAYOUT_SUCCESS = '/helper/earnings/payout/success';
  static const HELPER_PRIORITY = '/helper/priority';
  static const HELPER_SETTINGS_HELP_ACK = '/helper/settings/help-ack';
  static const DRIVER_DELIVERY_DETAIL = '/driver/delivery/detail';
}
